console.log("hacerun asado");
console.log("paso 1");
console.log("paso 2");
console.log("paso 3");
console.log("paso 4");
console.log("paso 5");
                console.log("algoritmo secuencial");
 console.log("hola");
 console.log("soy");
console.log("un");
  console.log("algoritmo");
  console.log("secuencial");
